### PR TITLE
Create ApelabsEdu

### PR DESCRIPTION
**Pull request by Aberzelius**
Let's go

### CODE REVIEW

**Comment by HansWuestenfuchs** [comment]
https://github.com/HansWuestenfuchs/raptoreum/commit/333193e59c79519edaa01cc39673aeebaeda020d

**Comment by Chimpin** [comment]
Hey hey heyyyyyyyy

**Review by Chimpin — COMMENTED** [review]
Very nice!

**Comment by Aberzelius** [comment]
Let the history be written here,
Shall we become thy best students, therefore thy hats (white ofc)

**Pull request merged**
